/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Mini Etherscan ***DEV***
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpResponse,
  delay,
  http
} from 'msw';



export const getGetAddressDangerDatabaseDeleteMockHandler = (overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<unknown> | unknown)) => {
  return http.delete('*/danger/database', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 200,
        
      })
  })
}
export const getDangerMock = () => [
  getGetAddressDangerDatabaseDeleteMockHandler()
]
